general.import = ["~/.config/omarchy/current/theme/alacritty.toml"]

[colors.bright]
black = "#586e75"
blue = "#839496"
cyan = "#93a1a1"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#657b83"

[colors.cursor]
cursor = "#839496"
text = "#002b36"

[colors.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[colors.primary]
background = "#002b36"
foreground = "#839496"

[env]
TERM = "xterm-256color"

[font]
normal = { family = "iA Writer Mono S" }
bold = { family = "iA Writer Mono S" }
italic = { family = "iA Writer Mono S" }
size = 12

[window]
opacity = 0.94

[window.padding]
x = 4
y = 4

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]
