#!/bin/bash

# Download temporal YADM bin if not locally installed
if ! [ -x "$(command -v yadm)" ]; then
  source <(curl -L bootstrap.yadm.io)
fi


### Initialize submodules...

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules..."
yadm submodule update --recursive --init
echo "Submodules initialized!"


# Source profile. TODO: Add support for shell detection
. ~/.bash_profile


# Install tmux-plugin-manager
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm


### Install Vim...

if [ -x "$(command -v vim)" ]; then
  echo "Bootstraping Vim..."
  vim '+PlugClean!' '+PlugUpdate' '+qall'
  echo "Vim bootstrapped!"
fi


## Configure fzf
cd ~/.fzf && ./install


### Decrypt files
yadm decrypt

# Import GPG keys
echo "Importing GPG keys..."
for key in "$HOME/.gnupg/*.gpg_key"; do
  gpg --import $key
done


### Change repository URL to SSH if has keys
echo "Updating the YADM repo origin URL"
yadm remote set-url origin "git@github.com:davafons/dotfiles"
