#!/bin/sh

# Locate YADM executable...
YADM="yadm"
if [ -f "/tmp/yadm" ]; then
	YADM="/tmp/yadm"
fi


### Initialize submodules...

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules..."
$YADM submodule update --recursive --init
echo "Submodules initialized!"


### Install Vim...

if command -v vim >/dev/null 2>&1; then
  echo "Bootstraping Vim..."
  vim '+PlugClean!' '+PlugUpdate' '+qall'
  echo "Vim bootstrapped!"
fi


### Decrypt files
$YADM decrypt

# Import GPG keys
echo "Importing GPG keys..."
for key in "$HOME/.gnupg/*.gpg_key"; do
  gpg --import $key
done

# Import SSH keys
echo "Importing SSH keys..."
eval $(ssh-agent -s)
for key in "$HOME/.ssh/*.key"; do
  ssh-add $key
done


### Change repository URL to SSH if has keys
if [ -n $(echo $HOME/.ssh/*.pub) ]; then
  echo "Updating the YADM repo origin URL"
  $YADM remote set-url origin "git@github.com:davafons/dotfiles"
fi
